/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ConnectorMqttEgress struct {
	// Size of the pool of MQTT clients that will publish messages to the remote broker.<br/><br/>Each MQTT client will be assigned 'clientid' of the form '${clientid_prefix}:${bridge_name}:egress:${node}:${n}'<br/>where 'n' is the number of a client inside the pool.
	PoolSize int32 `json:"pool_size,omitempty"`
	Local *ConnectorMqttEgressLocal `json:"local,omitempty"`
	Remote *ConnectorMqttEgressRemote `json:"remote"`
}
