/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse40026 struct {
	Code string `json:"code,omitempty"`
	// Bad request, possibly due to wrong parameters or the existence of a banned object.
	Message string `json:"message,omitempty"`
}
