/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ClusterCoreReplicants struct {
	// Core node name
	CoreNode string `json:"core_node,omitempty"`
	ReplicantNodes []ClusterReplicantInfo `json:"replicant_nodes,omitempty"`
}
