/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AuthzMetricsStatusFields struct {
	ResourceMetrics *AuthzResourceMetrics `json:"resource_metrics,omitempty"`
	// The metrics of the resource for each node.
	NodeResourceMetrics []AuthzNodeResourceMetrics `json:"node_resource_metrics,omitempty"`
	Metrics *AuthzMetrics `json:"metrics,omitempty"`
	// The metrics of the resource for each node.
	NodeMetrics []AuthzNodeMetrics `json:"node_metrics,omitempty"`
	// The status of the resource.
	Status string `json:"status,omitempty"`
	// The status of the resource for each node.
	NodeStatus []AuthzNodeStatus `json:"node_status,omitempty"`
	// The error of node.
	NodeError []AuthzNodeError `json:"node_error,omitempty"`
}
