/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AuthnJwtHmac struct {
	// JWT signing algorithm, Supports HMAC (configured as <code>hmac-based</code>) and RSA, ECDSA (configured as <code>public-key</code>).
	Algorithm string `json:"algorithm"`
	// The key to verify the JWT using HMAC algorithm.
	Secret string `json:"secret"`
	// Whether secret is base64 encoded.
	SecretBase64Encoded bool `json:"secret_base64_encoded,omitempty"`
	// Authentication mechanism.
	Mechanism string `json:"mechanism"`
	// JWT claim name to use for getting ACL rules.
	AclClaimName string `json:"acl_claim_name,omitempty"`
	// A list of custom claims to validate, which is a list of name/value pairs.<br/>Values can use the following placeholders:<br/>- <code>${username}</code>: Will be replaced at runtime with <code>Username</code> used by the client when connecting<br/>- <code>${clientid}</code>: Will be replaced at runtime with <code>Client ID</code> used by the client when connecting<br/>Authentication will verify that the value of claims in the JWT (taken from the Password field) matches what is required in <code>verify_claims</code>.
	VerifyClaims []string `json:"verify_claims,omitempty"`
	// Field to take JWT from.
	From string `json:"from,omitempty"`
	// Set to <code>true</code> or <code>false</code> to disable this auth provider.
	Enable bool `json:"enable,omitempty"`
}
