/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RetainerRetainer struct {
	// Enable retainer feature
	Enable bool `json:"enable,omitempty"`
	// Message retention time. This config is only applicable for messages without the Message Expiry Interval message property.<br/>0 means message will never expire.
	MsgExpiryInterval string `json:"msg_expiry_interval,omitempty"`
	// Interval for EMQX to scan expired messages and delete them. Never scan if the value is 0.
	MsgClearInterval string `json:"msg_clear_interval,omitempty"`
	// Maximum retained message size.
	MaxPayloadSize string `json:"max_payload_size,omitempty"`
	// When the retained flag of the `PUBLISH` message is set and Payload is empty,<br/>whether to continue to publish the message.<br/>See:<br/>http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718038
	StopPublishClearMsg bool `json:"stop_publish_clear_msg,omitempty"`
	// The maximum rate of delivering retained messages
	DeliveryRate string `json:"delivery_rate,omitempty"`
	Backend *RetainerMnesiaConfig `json:"backend,omitempty"`
}
