/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OneOfemqxRuleApiSchemaRuleTestContext struct {
    EmqxRuleApiSchemaCtxDeliveryDropped
    EmqxRuleApiSchemaCtxBridgeMqtt
    EmqxRuleApiSchemaCtxCheckAuthzComplete
    EmqxRuleApiSchemaCtxConnack
    EmqxRuleApiSchemaCtxDisconnected
    EmqxRuleApiSchemaCtxConnected
    EmqxRuleApiSchemaCtxDropped
    EmqxRuleApiSchemaCtxAcked
    EmqxRuleApiSchemaCtxDelivered
    EmqxRuleApiSchemaCtxUnsub
    EmqxRuleApiSchemaCtxSub
    EmqxRuleApiSchemaCtxPub
}
