/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BrokerDeflateOpts struct {
	// Compression level.
	Level string `json:"level,omitempty"`
	// Specifies the size of the compression state.<br/><br/>Lower values decrease memory usage per connection.
	MemLevel int32 `json:"mem_level,omitempty"`
	// Specifies the compression strategy.
	Strategy string `json:"strategy,omitempty"`
	// Takeover means the compression state is retained between server messages.
	ServerContextTakeover string `json:"server_context_takeover,omitempty"`
	// Takeover means the compression state is retained between client messages.
	ClientContextTakeover string `json:"client_context_takeover,omitempty"`
	// Specifies the size of the compression context for the server.
	ServerMaxWindowBits int32 `json:"server_max_window_bits,omitempty"`
	// Specifies the size of the compression context for the client.
	ClientMaxWindowBits int32 `json:"client_max_window_bits,omitempty"`
}
