/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EmqxMgmtApiNodesNodeInfo struct {
	// Node name
	Node string `json:"node,omitempty"`
	// Number of clients session in this node
	Connections int32 `json:"connections,omitempty"`
	// Number of clients currently connected to this node
	LiveConnections int32 `json:"live_connections,omitempty"`
	// CPU average load in 1 minute
	Load1 float64 `json:"load1,omitempty"`
	// CPU average load in 5 minute
	Load5 float64 `json:"load5,omitempty"`
	// CPU average load in 15 minute
	Load15 float64 `json:"load15,omitempty"`
	// File descriptors limit
	MaxFds int32 `json:"max_fds,omitempty"`
	// Allocated memory
	MemoryTotal string `json:"memory_total,omitempty"`
	// Used memory
	MemoryUsed string `json:"memory_used,omitempty"`
	// Node status
	NodeStatus string `json:"node_status,omitempty"`
	// Erlang/OTP version
	OtpRelease string `json:"otp_release,omitempty"`
	// Erlang processes limit
	ProcessAvailable int32 `json:"process_available,omitempty"`
	// Running Erlang processes
	ProcessUsed int32 `json:"process_used,omitempty"`
	// System uptime, milliseconds
	Uptime int32 `json:"uptime,omitempty"`
	// Release version
	Version string `json:"version,omitempty"`
	// Release edition
	Edition string `json:"edition,omitempty"`
	// Path to system files
	SysPath string `json:"sys_path,omitempty"`
	// Path to log files
	LogPath string `json:"log_path,omitempty"`
	// Node role
	Role string `json:"role,omitempty"`
}
