/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EmqxGatewayApiGatewayNodeStatus struct {
	// Node Name
	Node string `json:"node,omitempty"`
	// Gateway status
	Status string `json:"status,omitempty"`
	// The Gateway allowed maximum connections/clients
	MaxConnections int32 `json:"max_connections,omitempty"`
	// The Gateway current connected connections/clients
	CurrentConnections int32 `json:"current_connections,omitempty"`
}
