/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApiKeyBody struct {
	// Unique and format by [a-zA-Z0-9-_]
	Name string `json:"name,omitempty"`
	// No longer valid datetime
	ExpiredAt *OneOfapiKeyBodyExpiredAt `json:"expired_at,omitempty"`
	Desc string `json:"desc,omitempty"`
	// Enable/Disable
	Enable bool `json:"enable,omitempty"`
	// Expired
	Expired bool `json:"expired,omitempty"`
}
