/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse20013 struct {
	// Dashboard Auth Token
	Token string `json:"token,omitempty"`
	// EMQX Version
	Version string `json:"version,omitempty"`
	License *InlineResponse20013License `json:"license,omitempty"`
}
