/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EmqxDelayedApiMessage struct {
	// Delayed Message ID
	Msgid int32 `json:"msgid,omitempty"`
	// The node where message from
	Node string `json:"node,omitempty"`
	// Clinet publish message time, in RFC 3339 format
	PublishAt string `json:"publish_at,omitempty"`
	// Delayed interval(second)
	DelayedInterval int32 `json:"delayed_interval,omitempty"`
	// Delayed remaining(second)
	DelayedRemaining int32 `json:"delayed_remaining,omitempty"`
	// Expect publish time, in RFC 3339 format
	ExpectedAt string `json:"expected_at,omitempty"`
	// Topic
	Topic string `json:"topic,omitempty"`
	// QoS
	Qos int32 `json:"qos,omitempty"`
	// From ClientID
	FromClientid string `json:"from_clientid,omitempty"`
	// From Username
	FromUsername string `json:"from_username,omitempty"`
	// Payload, base64 encoded. Payload will be set to 'PAYLOAD_TO_LARGE' if its length is larger than 2048 bytes
	Payload string `json:"payload,omitempty"`
}
