/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RetainerMessageSummary struct {
	// Message ID.
	Msgid string `json:"msgid,omitempty"`
	// Topic.
	Topic string `json:"topic,omitempty"`
	// QoS.
	Qos int32 `json:"qos,omitempty"`
	// Message publish time, RFC 3339 format.
	PublishAt string `json:"publish_at,omitempty"`
	// The clientid of publisher.
	FromClientid string `json:"from_clientid,omitempty"`
	// The username of publisher.
	FromUsername string `json:"from_username,omitempty"`
}
