/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AuthnPostgresql struct {
	// Authentication mechanism.
	Mechanism string `json:"mechanism"`
	// Backend type.
	Backend string `json:"backend"`
	// Options for password hash verification.
	PasswordHashAlgorithm *OneOfauthnPostgresqlPasswordHashAlgorithm `json:"password_hash_algorithm,omitempty"`
	// SQL used to query data for authentication, such as password hash.
	Query string `json:"query"`
	// Set to <code>true</code> or <code>false</code> to disable this auth provider.
	Enable bool `json:"enable,omitempty"`
	// The IPv4 or IPv6 address or the hostname to connect to.<br/><br/>A host entry has the following form: `Host[:Port]`.<br/><br/>The PostgreSQL default port 5432 is used if `[:Port]` is not specified.
	Server string `json:"server"`
	// Database name.
	Database string `json:"database"`
	// Size of the connection pool towards the bridge target service.
	PoolSize int32 `json:"pool_size,omitempty"`
	// The username associated with the bridge in the external database used for authentication or identification purposes.
	Username string `json:"username"`
	// The password associated with the bridge, used for authentication with the external database.
	Password string `json:"password,omitempty"`
	// Deprecated. Enable automatic reconnect to the database.
	AutoReconnect bool `json:"auto_reconnect,omitempty"`
	Ssl *BrokerSslClientOpts `json:"ssl,omitempty"`
}
