/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2008 struct {
	Metrics *BridgeMetrics `json:"metrics,omitempty"`
	// Node metrics.
	NodeMetrics []BridgeNodeMetrics `json:"node_metrics,omitempty"`
}
