/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BridgeNodeStatus struct {
	// The node name.
	Node string `json:"node,omitempty"`
	Status string `json:"status,omitempty"`
	// This is the reason given in case a bridge is failing to connect.
	StatusReason string `json:"status_reason,omitempty"`
}
