/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DashboardHttps struct {
	// Port without IP(18083) or port with specified IP(127.0.0.1:18083).<br/>Disabled when setting bind to `0`.<br/>
	Bind string `json:"bind,omitempty"`
	SslOptions *DashboardSslOptions `json:"ssl_options"`
	// Socket acceptor pool size for TCP protocols. Default is the number of schedulers online
	NumAcceptors int32 `json:"num_acceptors,omitempty"`
	// Maximum number of simultaneous connections.
	MaxConnections int32 `json:"max_connections,omitempty"`
	// Defines the maximum length that the queue of pending connections can grow to.
	Backlog int32 `json:"backlog,omitempty"`
	// Send timeout for the socket.
	SendTimeout string `json:"send_timeout,omitempty"`
	// Enable IPv6 support, default is false, which means IPv4 only.
	Inet6 bool `json:"inet6,omitempty"`
	// Disable IPv4-to-IPv6 mapping for the listener.<br/>The configuration is only valid when the inet6 is true.
	Ipv6V6only bool `json:"ipv6_v6only,omitempty"`
	// Enable support for `HAProxy` header. Be aware once enabled regular HTTP requests can't be handled anymore.
	ProxyHeader bool `json:"proxy_header,omitempty"`
}
