/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EmqxRuleApiSchemaRuleEngine struct {
	// When set to 'true' (default), rule-engine will ignore messages published to $SYS topics.
	IgnoreSysMessage bool `json:"ignore_sys_message,omitempty"`
	// Default timeout for the `jq` rule engine function
	JqFunctionDefaultTimeout string `json:"jq_function_default_timeout,omitempty"`
}
