/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BrokerSysmonOs struct {
	// The time interval for the periodic CPU check.
	CpuCheckInterval string `json:"cpu_check_interval,omitempty"`
	// The threshold, as percentage of system CPU load,<br/> for how much system cpu can be used before the corresponding alarm is raised.
	CpuHighWatermark float64 `json:"cpu_high_watermark,omitempty"`
	// The threshold, as percentage of system CPU load,<br/> for how much system cpu can be used before the corresponding alarm is cleared.
	CpuLowWatermark float64 `json:"cpu_low_watermark,omitempty"`
	// The time interval for the periodic memory check.
	MemCheckInterval *OneOfbrokerSysmonOsMemCheckInterval `json:"mem_check_interval,omitempty"`
	// The threshold, as percentage of system memory,<br/> for how much system memory can be allocated before the corresponding alarm is raised.
	SysmemHighWatermark float64 `json:"sysmem_high_watermark,omitempty"`
	// The threshold, as percentage of system memory,<br/> for how much system memory can be allocated by one Erlang process before<br/> the corresponding alarm is raised.
	ProcmemHighWatermark float64 `json:"procmem_high_watermark,omitempty"`
}
