/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AuthnScram struct {
	// Authentication mechanism.
	Mechanism string `json:"mechanism"`
	// Backend type.
	Backend string `json:"backend"`
	// Hashing algorithm.
	Algorithm string `json:"algorithm,omitempty"`
	// Iteration count.
	IterationCount int32 `json:"iteration_count,omitempty"`
	// Set to <code>true</code> or <code>false</code> to disable this auth provider.
	Enable bool `json:"enable,omitempty"`
}
