/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2007 struct {
	Mqtt *BrokerMqtt `json:"mqtt,omitempty"`
	FlappingDetect *BrokerFlappingDetect `json:"flapping_detect,omitempty"`
	ForceShutdown *BrokerForceShutdown `json:"force_shutdown,omitempty"`
	ForceGc *BrokerForceGc `json:"force_gc,omitempty"`
}
