/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GatewayClientinfoOverride struct {
	// Template for overriding username.
	Username string `json:"username,omitempty"`
	// Template for overriding password.
	Password string `json:"password,omitempty"`
	// Template for overriding clientid.
	Clientid string `json:"clientid,omitempty"`
}
