/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ClusterReplicantInfo struct {
	// Replicant node name
	Node string `json:"node,omitempty"`
	// The number of RLOG (replicated log) streams
	Streams int32 `json:"streams,omitempty"`
}
