/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BrokerForceGc struct {
	// Enable forced garbage collection.
	Enable bool `json:"enable,omitempty"`
	// GC the process after this many received messages.
	Count int32 `json:"count,omitempty"`
	// GC the process after specified number of bytes have passed through.
	Bytes string `json:"bytes,omitempty"`
}
