/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UsersBody struct {
	// Dashboard Username
	Username string `json:"username,omitempty"`
	// Dashboard Password
	Password string `json:"password,omitempty"`
	// Dashboard User Description
	Description string `json:"description,omitempty"`
}
