/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ModulesDelayed struct {
	// Enable this feature
	Enable bool `json:"enable,omitempty"`
	// Maximum number of delayed messages (0 is no limit).
	MaxDelayedMessages int32 `json:"max_delayed_messages,omitempty"`
}
