/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EmqxRuleApiSchemaRuleTest struct {
	// The context of the event for testing
	Context *OneOfemqxRuleApiSchemaRuleTestContext `json:"context,omitempty"`
	// The SQL of the rule for testing
	Sql string `json:"sql"`
}
