/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RetainerMnesiaConfig struct {
	// Backend type.
	Type_ string `json:"type,omitempty"`
	// Specifies whether the messages are stored in RAM or persisted on disc.
	StorageType string `json:"storage_type,omitempty"`
	// Maximum number of retained messages. 0 means no limit.
	MaxRetainedMessages int32 `json:"max_retained_messages,omitempty"`
	// Retainer index specifications: list of arrays of positive ascending integers. Each array specifies an index. Numbers in an index specification are 1-based word positions in topics. Words from specified positions will be used for indexing.<br/>For example, it is good to have <code>[2, 4]</code> index to optimize <code>+/X/+/Y/...</code> topic wildcard subscriptions.
	IndexSpecs []int32 `json:"index_specs,omitempty"`
}
