/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EmqxAuthnSchemaMetrics struct {
	// The number of times the instance was ignored when the required authentication information was not found in the current instance.
	Nomatch int32 `json:"nomatch,omitempty"`
	// The total number of times the current instance was triggered.
	Total int32 `json:"total,omitempty"`
	// The required authentication information is found in the current instance, and the instance returns authentication success.
	Success int32 `json:"success,omitempty"`
	// The required authentication information is found in the current instance, and the instance returns authentication failure.
	Failed int32 `json:"failed,omitempty"`
	// The total rate at which instances are triggered, times/second.
	Rate float64 `json:"rate,omitempty"`
	// The highest trigger rate the instance has ever reached, times/second.
	RateMax float64 `json:"rate_max,omitempty"`
	// The average trigger rate of the instance within 5 minutes, times/second.
	RateLast5m float64 `json:"rate_last5m,omitempty"`
}
