/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AuthzMetrics struct {
	// The total number of times the authorization rule was triggered.
	Total int32 `json:"total,omitempty"`
	// The number of times the authentication was successful.
	Allow int32 `json:"allow,omitempty"`
	// The number of authentication failures.
	Deny int32 `json:"deny,omitempty"`
	// The number of times that no authorization rules were matched.
	Nomatch float64 `json:"nomatch,omitempty"`
	// The rate of matched, times/second.
	Rate float64 `json:"rate,omitempty"`
	// The max rate of matched, times/second.
	RateMax float64 `json:"rate_max,omitempty"`
	// The average rate of matched in the last 5 minutes, times/second.
	RateLast5m float64 `json:"rate_last5m,omitempty"`
}
