/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EmqxAuthzApiSchemaMongoRs struct {
	// Set to <code>true</code> or <code>false</code> to disable this ACL provider.
	Enable bool `json:"enable,omitempty"`
	// Backend type.
	Type_ string `json:"type"`
	// `MongoDB` collection containing the authorization data.
	Collection string `json:"collection"`
	// Conditional expression that defines the filter condition in the query.<br/>Filter supports the following placeholders:<br/> - <code>${username}</code>: Will be replaced at runtime with <code>Username</code> used by the client when connecting;<br/> - <code>${clientid}</code>: Will be replaced at runtime with <code>Client ID</code> used by the client when connecting.
	Filter *interface{} `json:"filter,omitempty"`
	// Replica set. Must be set to 'rs' when MongoDB server is running in 'replica set' mode.
	MongoType string `json:"mongo_type,omitempty"`
	// A Node list for Cluster to connect to. The nodes should be separated with commas, such as: `Node[,Node].`<br/>For each Node should be: The IPv4 or IPv6 address or the hostname to connect to.<br/>A host entry has the following form: `Host[:Port]`.<br/>The MongoDB default port 27017 is used if `[:Port]` is not specified.
	Servers string `json:"servers"`
	// Write mode.
	WMode string `json:"w_mode,omitempty"`
	// Read mode.
	RMode string `json:"r_mode,omitempty"`
	// Name of the replica set.
	ReplicaSetName string `json:"replica_set_name"`
	// Use DNS SRV record.
	SrvRecord bool `json:"srv_record,omitempty"`
	// Size of the connection pool towards the bridge target service.
	PoolSize int32 `json:"pool_size,omitempty"`
	// The username associated with the bridge in the external database used for authentication or identification purposes.
	Username string `json:"username,omitempty"`
	// The password associated with the bridge, used for authentication with the external database.
	Password string `json:"password,omitempty"`
	// Database name associated with the user's credentials.
	AuthSource string `json:"auth_source,omitempty"`
	// Database name.
	Database string `json:"database"`
	Topology *EmqxMongodbTopology `json:"topology,omitempty"`
	Ssl *BrokerSslClientOpts `json:"ssl,omitempty"`
}
