/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ListenersIdBody2 struct {
    ListenersWssRequiredBind
    ListenersWsRequiredBind
    ListenersTcpRequiredBind
    ListenersSslRequiredBind
    ListenersQuicRequiredBind
}
