/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GatewaysNameBody struct {
    EmqxGatewayApiUpdateExproto
    EmqxGatewayApiUpdateLwm2m
    EmqxGatewayApiUpdateCoap
    EmqxGatewayApiUpdateMqttsn
    EmqxGatewayApiUpdateStomp
    EmqxGatewayApiExproto
    EmqxGatewayApiLwm2m
    EmqxGatewayApiCoap
    EmqxGatewayApiMqttsn
    EmqxGatewayApiStomp
}
