/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AuthnJwtJwks struct {
	// Whether to use JWKS.
	UseJwks string `json:"use_jwks"`
	// JWKS endpoint, it's a read-only endpoint that returns the server's public key set in the JWKS format.
	Endpoint string `json:"endpoint"`
	// Size of the connection pool towards the bridge target service.
	PoolSize int32 `json:"pool_size,omitempty"`
	// JWKS refresh interval.
	RefreshInterval int32 `json:"refresh_interval,omitempty"`
	Ssl *BrokerSslClientOpts `json:"ssl,omitempty"`
	// Authentication mechanism.
	Mechanism string `json:"mechanism"`
	// JWT claim name to use for getting ACL rules.
	AclClaimName string `json:"acl_claim_name,omitempty"`
	// A list of custom claims to validate, which is a list of name/value pairs.<br/>Values can use the following placeholders:<br/>- <code>${username}</code>: Will be replaced at runtime with <code>Username</code> used by the client when connecting<br/>- <code>${clientid}</code>: Will be replaced at runtime with <code>Client ID</code> used by the client when connecting<br/>Authentication will verify that the value of claims in the JWT (taken from the Password field) matches what is required in <code>verify_claims</code>.
	VerifyClaims []string `json:"verify_claims,omitempty"`
	// Field to take JWT from.
	From string `json:"from,omitempty"`
	// Set to <code>true</code> or <code>false</code> to disable this auth provider.
	Enable bool `json:"enable,omitempty"`
}
