/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EmqxGatewayApiGatewayListenerOverview struct {
	// Listener ID
	Id string `json:"id,omitempty"`
	// Listener Running status
	Running bool `json:"running,omitempty"`
	// Listener Type
	Type_ string `json:"type,omitempty"`
}
