/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ExhookMetrics struct {
	// The number of times the hooks execution successful
	Succeed int32 `json:"succeed,omitempty"`
	// The number of times the hook execution failed
	Failed int32 `json:"failed,omitempty"`
	// The call rate of hooks
	Rate int32 `json:"rate,omitempty"`
	// Maximum call rate of hooks
	MaxRate int32 `json:"max_rate,omitempty"`
}
