/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApiKeyApp struct {
	// Unique and format by [a-zA-Z0-9-_]
	Name string `json:"name,omitempty"`
	// TODO:uses HMAC-SHA256 for signing.
	ApiKey string `json:"api_key,omitempty"`
	// An API secret is a simple encrypted string that identifiesan application without any principal.They are useful for accessing public data anonymously,and are used to associate API requests.
	ApiSecret string `json:"api_secret,omitempty"`
	// No longer valid datetime
	ExpiredAt *OneOfapiKeyAppExpiredAt `json:"expired_at,omitempty"`
	// ApiKey create datetime
	CreatedAt *OneOfapiKeyAppCreatedAt `json:"created_at,omitempty"`
	Desc string `json:"desc,omitempty"`
	// Enable/Disable
	Enable bool `json:"enable,omitempty"`
	// Expired
	Expired bool `json:"expired,omitempty"`
}
