/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PrometheusPrometheus struct {
	// URL of Prometheus server. Pushgateway is optional, should not be configured if prometheus is to scrape EMQX.
	PushGatewayServer string `json:"push_gateway_server"`
	// Data reporting interval
	Interval string `json:"interval"`
	// An HTTP Headers when pushing to Push Gateway.<br/><br/>For example, <code> { Authorization = \"some-authz-tokens\"}</code>
	Headers []interface{} `json:"headers,omitempty"`
	// Job Name that is pushed to the Push Gateway. Available variables:<br/><br/>- ${name}: Name of EMQX node.<br/><br/>- ${host}: Host name of EMQX node.<br/><br/>For example, when the EMQX node name is <code>emqx@127.0.0.1</code> then the <code>name</code> variable takes value <code>emqx</code> and the <code>host</code> variable takes value <code>127.0.0.1</code>.<br/><br/>Default value is: <code>${name}/instance/${name}~${host}</code>
	JobName string `json:"job_name"`
	// Turn Prometheus data pushing on or off
	Enable bool `json:"enable"`
	// Enable or disable VM distribution collector, collects information about the sockets and processes involved in the Erlang distribution mechanism.
	VmDistCollector string `json:"vm_dist_collector"`
	// Enable or disable Mnesia metrics collector
	MnesiaCollector string `json:"mnesia_collector"`
	// Enable or disable VM statistics collector.
	VmStatisticsCollector string `json:"vm_statistics_collector"`
	// Enable or disable VM system info collector.
	VmSystemInfoCollector string `json:"vm_system_info_collector"`
	// Enable or disable VM memory metrics collector.
	VmMemoryCollector string `json:"vm_memory_collector"`
	// Enable or disable VM microstate accounting metrics collector.
	VmMsaccCollector string `json:"vm_msacc_collector"`
}
