/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PublicMeta struct {
	// Page number of the results to fetch.
	Page int32 `json:"page,omitempty"`
	// Results per page(max 1000)
	Limit int32 `json:"limit,omitempty"`
	// Total number of records matching the query.<br/>Note: this field is present only if the query can be optimized and does not require a full table scan.
	Count int32 `json:"count,omitempty"`
	// Flag indicating whether there are more results available on next pages.
	Hasnext bool `json:"hasnext"`
}
