/*
 * EMQX API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse20011 struct {
	// Message ID
	Id int32 `json:"id,omitempty"`
	// Message token, can be empty
	Token string `json:"token,omitempty"`
	// Response code
	Method string `json:"method,omitempty"`
	// The content of the payload
	Payload string `json:"payload,omitempty"`
}
